trigger:
  - main  # Fixed typo in the trigger name!

resources:
  - repo: self

pool:
  name: Default
  demands:
    - Agent.Name -equals DESKTOP-DDVOVCD  # Corrected syntax

variables:
  tag: 'latest'
  build_config: '' # Default value, can be overridden in the release pipeline
  imageName: 'poc-node'

stages:
- stage: Build
  displayName: 'Build Docker image and Push Image'
  jobs:
  - job: Build
    steps:
    - script: |
        npm cache clean --force
        npm install
      displayName: 'Clean NPM Cache and Install Dependencies'

    - task: Docker@2     # start Building Docker Image
      displayName: 'Build container image2'
      inputs:
        containerRegistry: 'service-connect-acr'
        repository: 'poc-node'
        command: 'build'
        Dockerfile: '**/Dockerfile'  # Build a Docker image from the provided Dockerfile
        buildContext: '$(Build.SourcesDirectory)'
        tags: '$(tag)'
        arguments: '--build-arg build_config=$(build_config)'  # Pass build_config as a build argument (used for different environments).  # end Building Docker Image

    - task: Docker@2    # start Push Docker Image to ACR
      displayName: 'Push container image3'
      inputs:
        containerRegistry: 'service-connect-acr'
        repository: 'poc-node'
        command: 'push'
        tags: '$(tag)'    # end // purpose : Pushes the built Docker image to Azure Container Registry (ACR), making it available for deployment.
   
                
    - task: CopyFiles@2   #  strt Copy Kubernetes YAML Files
      inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '*.yml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/helm'   # end  // Copies all Kubernetes YAML configuration files (*.yml) to a temporary build directory (Build.ArtifactStagingDirectory).
          # old TargetFolder: '$(Build.ArtifactStagingDirectory)/*.yml'   # end  // Copies all Kubernetes YAML configuration files (*.yml) to a temporary build directory (Build.ArtifactStagingDirectory).

    